const ROLES = {
  VICTIM: 'victim',
  VOLUNTEER: 'volunteer',
  NGO: 'ngo',
  HOSPITAL: 'hospital',
  AUTHORITY: 'authority',
  ADMIN: 'admin',
};

const ROLE_LIST = Object.values(ROLES);
const PUBLIC_REGISTRATION_ROLES = [ROLES.VICTIM, ROLES.VOLUNTEER, ROLES.NGO, ROLES.HOSPITAL];
const APPROVAL_REQUIRED_ROLES = [ROLES.VOLUNTEER, ROLES.NGO, ROLES.HOSPITAL, ROLES.AUTHORITY];

module.exports = { ROLES, ROLE_LIST, PUBLIC_REGISTRATION_ROLES, APPROVAL_REQUIRED_ROLES };
